{"name": "test_demo2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_Demo.TestDemo object at 0x7f1b41a51cf8>\n\n    @allure.step(\"test demo Two\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_demo2(self):\n        print(\"i am test_demo2\")\n>       assert False\nE       assert False\n\ntest_Demo.py:15: AssertionError"}, "steps": [{"name": "test demo Two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"/local/tools/Python-3.6.9/software/python3.6/lib/python3.6/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/local/sda/appium_test/test_case/test_Demo.py\", line 15, in test_demo2\n    assert False\n"}, "start": 1567512935913, "stop": 1567512935913}], "start": 1567512935913, "stop": 1567512935914, "uuid": "279b8f43-1051-40ff-a5c3-4f59e4ebd794", "historyId": "519ae16d357cdb12d276458e6a29b746", "testCaseId": "6e44e5597a5bddd05d47121c694130b9", "fullName": "test_case.test_Demo.TestDemo#test_demo2", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_Demo"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "10286-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_Demo"}]}